### ISSUE TITLE
Kotlin compilation error in module spring-cloud-function-context after upgrading to Spring Cloud 2023.0.4

### ISSUE THREAD

**Issue by beytularedzheb** [spring-cloud/spring-cloud-stream#3051]
**Description**
After upgrading the spring cloud dependencies from 2023.0.3 to 2023.0.4 I started getting below compilation error in few projects of mine which use spring cloud stream.

> [ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.9.25:compile (compile) on project xxx: Compilation failure
> [ERROR] /Users/xxx/.m2/repository/org/springframework/cloud/spring-cloud-function-context/4.1.4/spring-cloud-function-context-4.1.4.jar!/META-INF/spring-cloud-function-context.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0.

Given that the recommended kotlin version in spring boot 3.3.X is 1.9.25 and spring cloud 2023.0.4 is based on spring boot 3.2.12 and 3.3.6 I think it should not require kotlin 2.1.0 which was released just a few days ago (27.11.2024).

**Version of the framework**
- Spring Boot 3.3.6
- Spring Cloud: 2023.0.4
- Kotlin: 1.9.25
- Java: 17

**Expected behavior**
No compilation error

**Comment by olegz** [comment]
That is strange since we do not specify version of Kotlin anywhere in spring-cloud-functon and instead inherit it. I suspect something upstream (e.g., boot)?

**Comment by beytularedzheb** [comment]
It looks like I am not the only one having this issue - https://github.com/spring-cloud/spring-cloud-function/issues/1218

**Comment by olegz** [comment]
See my comment in that issue. It appears something has changed upstream and it's working with 2024.0.1-SNAPSHOT of cloud.

**Comment by olegz** [comment]
Versions were explicitly added - https://github.com/spring-cloud/spring-cloud-function/commit/0a43fc92d547055af8b07ce591ba9d60550bb377
