### ISSUE TITLE
Update Spring Cloud Stream version from 3.2.6 to 4.0.4 ,compilation error occurred in the project

### ISSUE THREAD

**Issue by keepGOG** [spring-cloud/spring-cloud-stream#2887]
the old version of the spring cloud stream is 3.2.6 and import the spring-cloud-stream-test-support to do unit test.
 After updated the version to 4.0.3, the compilation error occurs: package org.springframework.cloud.stream.test.binder does not exist, the related class can't be found. 
Is the higher version not compatible with old code? 
if yes, is there an alternative class available to replace that ?

**Comment by sobychacko** [comment]
@keepGOG testing components have moved into its dedicated module - `spring-cloud-stream-test-binder.` More details here: https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_testing
Since `4.0.x` was a major release, we decided to clean up a few things on the testing front. Please update your code if need be. If things work for you after making these changes, please close this issue.

**Comment by keepGOG** [comment]
not found suitable write way to replace. would you tell me the replacement of the following:
Message<?> msg = collector.forChannel(channel).poll(1, TimeUnit.SECONDS);
the collector is the instance of org.springframework.cloud.stream.test.binder.MessageCollector, the channel is the instance of org.springframework.messaging.MessageChannel.
thanks very much If you can provide any help @sobychacko

**Comment by sobychacko** [comment]
All those old testing components had been deprecated for a while and then finally got removed in `4.0.x` version of the framework. You should use the approaches used in this [test](https://github.com/spring-cloud/spring-cloud-stream/blob/main/core/spring-cloud-stream-integration-tests/src/test/java/org/springframework/cloud/stream/function/ImplicitFunctionBindingTests.java) for example. Basically, use `InputDestination` to send the data and `OutputDestination` to collect the data. These destinations are bound via the Spring Integration Channel based test binder.

**Comment by keepGOG** [comment]
the issue has been resolved, thanks a lot for your reply.
